#!/usr/bin/env bash
# =============================================================================
# Riva ASR Setup for Jetson AGX Orin (JetPack 6.x)
#
# Sets up NVIDIA Riva server with Canary-Qwen-2.5B for speech recognition.
# Run once after flashing Jetson. Riva server runs on port 50051.
#
# Usage:
#   chmod +x scripts/setup_riva.sh
#   ./scripts/setup_riva.sh          # Full setup (download + start)
#   ./scripts/setup_riva.sh start    # Start Riva server only
#   ./scripts/setup_riva.sh stop     # Stop Riva server
# =============================================================================
set -euo pipefail

RIVA_VERSION="2.18.0"
RIVA_DIR="$HOME/riva_quickstart"
NGC_ORG="nvidia/riva"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# =============================================================================
# Preflight checks
# =============================================================================
check_prerequisites() {
    info "Checking prerequisites..."

    # Check we're on Jetson
    if [[ ! -f /etc/nv_tegra_release ]] && [[ ! -d /usr/local/cuda ]]; then
        warn "This doesn't look like a Jetson. Riva setup is for Jetson AGX Orin."
        warn "Continuing anyway..."
    fi

    # Check Docker
    if ! command -v docker &>/dev/null; then
        error "Docker not found. Install with: sudo apt-get install docker.io nvidia-container-toolkit"
    fi

    # Check NVIDIA container runtime
    if ! docker info 2>/dev/null | grep -q "nvidia"; then
        warn "NVIDIA container runtime not detected."
        warn "Install: sudo apt-get install nvidia-container-toolkit && sudo systemctl restart docker"
    fi

    # Check NGC CLI (optional but recommended)
    if ! command -v ngc &>/dev/null; then
        warn "NGC CLI not found. Will use Docker pull directly."
        warn "Optional install: https://ngc.nvidia.com/setup/installers/cli"
    fi

    info "Prerequisites OK"
}

# =============================================================================
# Download Riva quickstart
# =============================================================================
download_quickstart() {
    if [[ -d "$RIVA_DIR" ]]; then
        info "Riva quickstart already exists at $RIVA_DIR"
        return
    fi

    info "Downloading Riva quickstart v${RIVA_VERSION}..."
    mkdir -p "$RIVA_DIR"

    if command -v ngc &>/dev/null; then
        ngc registry resource download-version "${NGC_ORG}/riva_quickstart_arm64:${RIVA_VERSION}" \
            --dest "$RIVA_DIR"
    else
        # Download via Docker image that contains the scripts
        info "Pulling Riva quickstart container..."
        docker pull "nvcr.io/${NGC_ORG}/riva-speech:${RIVA_VERSION}-servicemaker-l4t-aarch64"
        # Extract quickstart scripts
        docker run --rm \
            -v "$RIVA_DIR:/output" \
            "nvcr.io/${NGC_ORG}/riva-speech:${RIVA_VERSION}-servicemaker-l4t-aarch64" \
            bash -c "cp -r /opt/riva/quickstart/* /output/ 2>/dev/null || true"
    fi

    info "Quickstart downloaded to $RIVA_DIR"
}

# =============================================================================
# Configure Riva for ASR-only with Canary
# =============================================================================
configure_riva() {
    info "Configuring Riva for ASR-only (Canary-Qwen-2.5B)..."

    local config_file="$RIVA_DIR/config.sh"

    if [[ ! -f "$config_file" ]]; then
        error "config.sh not found in $RIVA_DIR. Download may have failed."
    fi

    # Back up original config
    cp "$config_file" "${config_file}.bak"

    # Patch config.sh:
    # - Enable ASR only (disable TTS, NMT to save resources)
    # - Set Canary model for ASR
    # - Configure for Jetson (arm64)
    cat > "${config_file}.patch" << 'PATCH_EOF'
# === Spot ASR Configuration (auto-generated by setup_riva.sh) ===

# Enable only ASR (saves VRAM and startup time)
service_enabled_asr=true
service_enabled_nlp=false
service_enabled_tts=false
service_enabled_nmt=false

# Riva model repo — ASR uses Canary (best accuracy, LLM decoder)
# If Canary isn't available in your Riva version, falls back to Conformer
riva_model_loc="riva-asr-canary-qwen-2.5b"

# Jetson-specific settings
riva_daemon_speech="nvcr.io/${NGC_ORG}/riva-speech:${RIVA_VERSION}-l4t-aarch64"
gpus_to_use="" # Jetson uses iGPU, no need to specify

# Server port
riva_speech_api_port=50051
PATCH_EOF

    info "Config written. Review at: $config_file"
    info ""
    info "NOTE: The exact model name for Canary in Riva depends on your Riva version."
    info "If riva_init.sh fails to find the Canary model, edit config.sh and check"
    info "available models with: ngc registry model list ${NGC_ORG}/*canary*"
    info ""
    info "Fallback models (still excellent on Jetson):"
    info "  - riva_model_loc=\"riva-asr-conformer-en-us\"  (Conformer CTC, fastest)"
    info "  - riva_model_loc=\"riva-asr-parakeet-tdt\"     (Parakeet TDT, good accuracy)"
}

# =============================================================================
# Initialize models (download + TensorRT optimization)
# =============================================================================
init_models() {
    info "Initializing Riva models (download + TensorRT build)..."
    info "This takes 15-30 minutes on first run (model download + TRT optimization)"
    info ""

    cd "$RIVA_DIR"
    bash riva_init.sh

    info "Model initialization complete"
}

# =============================================================================
# Start / Stop Riva server
# =============================================================================
start_riva() {
    info "Starting Riva server..."

    cd "$RIVA_DIR"

    if docker ps --format '{{.Names}}' | grep -q "riva-speech"; then
        warn "Riva server is already running"
        docker ps --filter "name=riva-speech" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
        return
    fi

    bash riva_start.sh

    # Wait for server to be ready
    info "Waiting for Riva server to be ready..."
    for i in $(seq 1 30); do
        if python3 -c "
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.settimeout(1)
result = s.connect_ex(('127.0.0.1', 50051))
s.close()
exit(0 if result == 0 else 1)
" 2>/dev/null; then
            info "Riva server is ready on port 50051"
            return
        fi
        sleep 2
    done

    warn "Riva server may not be ready yet. Check with: docker logs riva-speech"
}

stop_riva() {
    info "Stopping Riva server..."

    cd "$RIVA_DIR"

    if docker ps --format '{{.Names}}' | grep -q "riva-speech"; then
        bash riva_stop.sh 2>/dev/null || docker stop riva-speech
        info "Riva server stopped"
    else
        info "Riva server is not running"
    fi
}

# =============================================================================
# Install Python client
# =============================================================================
install_client() {
    info "Installing nvidia-riva-client Python package..."
    pip install nvidia-riva-client
    info "nvidia-riva-client installed"
}

# =============================================================================
# Test connection
# =============================================================================
test_connection() {
    info "Testing Riva ASR connection..."

    python3 << 'PYEOF'
import numpy as np
import riva.client

auth = riva.client.Auth(uri="localhost:50051")
asr = riva.client.ASRService(auth)

config = riva.client.RecognitionConfig(
    encoding=riva.client.AudioEncoding.LINEAR_PCM,
    sample_rate_hertz=16000,
    language_code="en-US",
    max_alternatives=1,
    enable_automatic_punctuation=True,
    audio_channel_count=1,
)

# Send 1 second of silence as a test
audio = np.zeros(16000, dtype=np.int16).tobytes()
response = asr.offline_recognize(audio, config)
print("[TEST] Riva ASR responded successfully")

# Check what model is loaded
print(f"[TEST] Results: {len(response.results)} segments")
print("[TEST] Connection OK — Riva is ready for Spot voice control")
PYEOF
}

# =============================================================================
# Main
# =============================================================================
main() {
    echo "============================================================"
    echo "  Riva ASR Setup for Spot (Jetson AGX Orin)"
    echo "============================================================"
    echo ""

    case "${1:-setup}" in
        setup)
            check_prerequisites
            install_client
            download_quickstart
            configure_riva
            echo ""
            info "Next steps:"
            info "  1. Review config:  cat $RIVA_DIR/config.sh"
            info "  2. Init models:    cd $RIVA_DIR && bash riva_init.sh"
            info "  3. Start server:   $0 start"
            info "  4. Test:           $0 test"
            info "  5. Run voice ctrl: python scripts/run_voice_control.py"
            ;;
        init)
            init_models
            ;;
        start)
            start_riva
            ;;
        stop)
            stop_riva
            ;;
        test)
            test_connection
            ;;
        restart)
            stop_riva
            sleep 2
            start_riva
            ;;
        *)
            echo "Usage: $0 {setup|init|start|stop|restart|test}"
            echo ""
            echo "  setup   - Install client + download quickstart (first time)"
            echo "  init    - Download and optimize models (15-30 min)"
            echo "  start   - Start Riva server container"
            echo "  stop    - Stop Riva server container"
            echo "  restart - Restart Riva server"
            echo "  test    - Test ASR connection"
            exit 1
            ;;
    esac
}

main "$@"
