# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asr.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'asr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tasr.proto\x12\x03\x61sr\"\\\n\x0fStreamingConfig\x12\x15\n\rlanguage_code\x18\x01 \x01(\t\x12\x16\n\x0esample_rate_hz\x18\x02 \x01(\x05\x12\x1a\n\x12\x65nable_punctuation\x18\x03 \x01(\x08\"\x1b\n\nAudioChunk\x12\r\n\x05pcm16\x18\x01 \x01(\x0c\"g\n\x10StreamingRequest\x12&\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x14.asr.StreamingConfigH\x00\x12 \n\x05\x61udio\x18\x02 \x01(\x0b\x32\x0f.asr.AudioChunkH\x00\x42\t\n\x07request\"L\n\x11StreamingResponse\x12\x10\n\x08is_final\x18\x01 \x01(\x08\x12\x12\n\ntranscript\x18\x02 \x01(\t\x12\x11\n\tstability\x18\x03 \x01(\x02\x32N\n\x03\x41SR\x12G\n\x12StreamingRecognize\x12\x15.asr.StreamingRequest\x1a\x16.asr.StreamingResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMINGCONFIG']._serialized_start=18
  _globals['_STREAMINGCONFIG']._serialized_end=110
  _globals['_AUDIOCHUNK']._serialized_start=112
  _globals['_AUDIOCHUNK']._serialized_end=139
  _globals['_STREAMINGREQUEST']._serialized_start=141
  _globals['_STREAMINGREQUEST']._serialized_end=244
  _globals['_STREAMINGRESPONSE']._serialized_start=246
  _globals['_STREAMINGRESPONSE']._serialized_end=322
  _globals['_ASR']._serialized_start=324
  _globals['_ASR']._serialized_end=402
# @@protoc_insertion_point(module_scope)
